### ISSUE TITLE
Generic model breaks when subclassing is introduced

### ISSUE THREAD

**Issue by tciuro** [chili-ios/MDL11_Generics#1]
Hello,

Following your project, I was trying to reuse the cells by subclassing. Like so:

	class BaseCell: UITableViewCell, ConfigurableCell {
		func configure(item: Base) {
			imageView?.image = item.image
			textLabel?.text = item.text
			detailTextLabel?.text = item.detail
		}
	}

	class Base {
		let image: UIImage?
		let text: String?
		let detail: String?
	
		init(image: UIImage?, text: String?, detail: String?) {
			self.image = image
			self.text = text
			self.detail = detail
		}
	}

then I modified the `User` class like so:

	class UserCell: BaseCell {}

	class User: Base {
		init(name: String, imageName: String) {
			super.init(image: UIImage(named: imageName), text: name, detail: nil)
		}
	}

The idea is simple: reuse UITableViewCell's `imageView`, `textLabel` and `detailLabel` while keeping the model semantics that's right for the app (e.g. `User`).

The problem appears in this line:

    typealias UserCellConfig = TableCellConfigurator<UserCell, User>

Error:

    'TableCellConfigurator' requires the types 'User' and 'Base' be equivalent.
    Requirement specified as 'ItemType' == 'CellType.ItemType'
    [with CellType = UserCell, ItemType = User]

Looks like the comparison is too strict and doesn't count for the fact that User _is a_ Base. There's got to be a way to accomplish this, but it escapes me.

**Comment by chili-ios** [comment]
hi @tciuro ,

I'm not sure if that is possible to accomplish. There is another question, why do you need to separate cells with the same UI? I would better make one cell with a view model and add the manipulations with the data there.
